contents:
  packages:
    - ca-certificates-bundle
    - wolfi-baselayout
    - tzdata
    - nodejs-22
    - catatonit

environment:
  PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt
