name: Build Docker Image

on: 
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"
jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      packages: write
      contents: read
      attestations: write
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    
    steps:
      - name: Generate snapshot date
        id: snapshot-date
        run: |
          echo "epoch=$(date -u +%s)" >> $GITHUB_OUTPUT
        shell: bash
            
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
  
      - uses: distroless/actions/apko-snapshot@main
        id: apko
        with:
          source-date-epoch: ${{ steps.snapshot-date.outputs.epoch }}
          additional-tags: 1.0.0
          archs: amd64
          slsa-attest: "true"
          sbom-attest: "true"
          build-repository-append: https://packages.darkfellanetwork.com
          keyring-append: https://packages.darkfellanetwork.com/melange.rsa.pub
  
      - name: Generate Trivy Vulnerability Report
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.apko.outputs.digest }}
          output: trivy-report.json
          format: json
          exit-code: 0
          vuln-type: 'os,library'

      - name: Upload Vulnerability Scan Results
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.json
          retention-days: 30
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.apko.outputs.digest }}
          format: 'table'
          exit-code: '1'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
